### ISSUE TITLE
Gemfile doesn't specify `y_support` gem as a dependency

### ISSUE THREAD

**Issue by WilHall** [boris-s/sy#1]
The Gemfile for this gem does not specify `y_support` as a dependency, thus `require 'sy'` in a fresh environment yields:

```
irb(main):002:0> require 'sy'
LoadError: cannot load such file -- y_support/null_object
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/sy-2.1.2/lib/sy.rb:3:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from (irb):2
    from /usr/local/bin/irb:11:in `<main>'
```

unless the `y_support` gem is manually installed.

**Comment by boris-s** [comment]
Thanks for your reminder. I'll take a look into it.

**Comment by boris-s** [comment]
I have added YSupport in the .gemspec file. Thank you for reporting the issues. At the same time, I edited y_support gem to remove the issues caused by the new Ruby version. Thanks again.
