### ISSUE TITLE
Error when importing: "NoMethodError: undefined method `quantity' for nil:NilClass"

### ISSUE THREAD

**Issue by WilHall** [boris-s/sy#2]
After manually installing `y_support` which is required, but not listed as a dependency for the gem (see #1), I am unable to `require 'sy'` or `require 'sy/noimport'`; both yield the same `NoMethodError`:

```
irb(main):001:0> require 'sy/noinclude'
/usr/local/lib/ruby/gems/2.3.0/gems/y_support-2.1.18/lib/y_support/name_magic/namespace_methods.rb:245: warning: constant ::TimeoutError is deprecated
/usr/local/lib/ruby/gems/2.3.0/gems/y_support-2.1.18/lib/y_support/name_magic/namespace_methods.rb:245: warning: constant ::TimeoutError is deprecated
/usr/local/lib/ruby/gems/2.3.0/gems/y_support-2.1.18/lib/y_support/name_magic/namespace_methods.rb:245: warning: constant ::TimeoutError is deprecated
/usr/local/lib/ruby/gems/2.3.0/gems/y_support-2.1.18/lib/y_support/name_magic/namespace_methods.rb:245: warning: constant ::TimeoutError is deprecated
NoMethodError: undefined method `quantity' for nil:NilClass
    from /usr/local/lib/ruby/gems/2.3.0/gems/sy-2.1.2/lib/sy/magnitude.rb:50:in `<=>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/y_support-2.1.18/lib/y_support/name_magic/class_methods.rb:177:in `=='
    from /usr/local/lib/ruby/gems/2.3.0/gems/y_support-2.1.18/lib/y_support/name_magic/class_methods.rb:177:in `include?'
    from /usr/local/lib/ruby/gems/2.3.0/gems/y_support-2.1.18/lib/y_support/name_magic/class_methods.rb:177:in `new'
    from /usr/local/lib/ruby/gems/2.3.0/gems/sy-2.1.2/lib/sy/quantity.rb:279:in `unit'
    from /usr/local/lib/ruby/gems/2.3.0/gems/sy-2.1.2/lib/sy/quantity.rb:302:in `new_standard_unit'
    from /usr/local/lib/ruby/gems/2.3.0/gems/sy-2.1.2/lib/sy/unit.rb:100:in `standard'
    from /usr/local/lib/ruby/gems/2.3.0/gems/sy-2.1.2/lib/sy.rb:87:in `<module:SY>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/sy-2.1.2/lib/sy.rb:66:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/sy-2.1.2/lib/sy/noinclude.rb:10:in `require_relative'
    from /usr/local/lib/ruby/gems/2.3.0/gems/sy-2.1.2/lib/sy/noinclude.rb:10:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from (irb):1
    from /usr/local/bin/irb:11:in `<main>'
```

**Comment by boris-s** [comment]
I suspect this error was caused by different implementation of some methods in the newer Ruby versions. I made changes to SY to solve this issue. I am also working on the new major version of SY, but it will take some time.
